version: '3.7'
services:
  app:
    build: .
    container_name: socket.io-cookies
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webnet
    environment:
      NODE_ENV: development
    command:
      - npm
      - run
      - watch

networks:
  webnet:
